### ISSUE TITLE
Does it work if I use the plugin only in the proxy?

### ISSUE THREAD

**Issue by jd07159** [Bram1903/AntiHealthIndicator#10]
Do I need to install the plugin on the backend server as well?

First of all, I installed and run the plugin only on the proxy server, but it does not work.

**Comment by jd07159** [comment]
config 
players-only: enabled: true
I've set this up and tested it, but the health feature doesn't work - the rest seems to work.

my english is not very good.

**Comment by Bram1903** [comment]
Hey there, 

Yeah, the plugin only needs to be installed on the proxy. First try it with the default config. Players only means that only other players there health is being spoofed, but it won't spoof the health of other entities. So first give it a shot with the default config. Simply remove the file if you aren't sure what settings to use. What platform is your proxy? 

Kind regards,
Bram

**Comment by jd07159** [comment]
Using velocity
playeronly: false
Works fine.
But I only want it to work for the player.

**Comment by jd07159** [comment]
And it doesn't seem to be compatible with Geyser either.
This error appears only for BE users.

```[06:28:29 INFO] [geyser]: NeededBus978018 has disconnected from the Java server because of §r§c연결에 내부 오류가 발생했습니다.
[06:28:29 ERROR]: [connected player] .NeededBus978018 (/211.204.147.155:0): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@5269b261
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at org.geysermc.geyser.network.netty.ChannelWrapper.write(ChannelWrapper.java:209) ~[?:?]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:249) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:445) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:161) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.writeMappedEntityOrDirect(PacketWrapper.java:1409) ~[?:?]
        at com.github.retrooper.packetevents.protocol.component.builtin.item.BannerLayers$Layer.write(BannerLayers.java:89) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.writeList(PacketWrapper.java:1371) ~[?:?]
        at com.github.retrooper.packetevents.protocol.component.builtin.item.BannerLayers.write(BannerLayers.java:43) ~[?:?]
        at com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.write(ComponentTypes.java:90) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStackModern(PacketWrapper.java:502) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStack(PacketWrapper.java:527) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.writeEntityMetadata(PacketWrapper.java:934) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.write(WrapperPlayServerEntityMetadata.java:62) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:51) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:68) ~[?:?]
        at io.github.retrooper.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:32) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
        ... 49 more```

**Comment by Bram1903** [comment]
Hey there, 

The players only option should work fine, but I am going to look into that for you in half a hour. 

About geyser, do you only have the Geyser plugin on the backend server? It's probably not yet converting the packets to a readable format for PE, and since the Proxy handles the connection first that might be the issue. I am going to look into this as well!

Thanks for the feedback,
Bram

**Comment by jd07159** [comment]
No, the geyser plugin only works on proxy servers.
We will use this on the backend until the issue is resolved.
thank you

**Comment by jd07159** [comment]
I also set playeronly:true on the backend server, but the player's health was not spoofed.

**Comment by Bram1903** [comment]
> I also set playeronly:true on the backend server, but the player's health was not spoofed.

Hey, 

I perhaps missed something while rewriting the configuration manager. I am currently eating breakfast, and I'll test it right afterwards. If this is a mistake I will release a new build that fixes this issue in around 30 minutes, or so.

Regards,
Bram

**Comment by Bram1903** [comment]
Hello,

The players only option indeed wasn't working as expected. In the latest commit, I fixed this issue. 
Could you give this build a try? 

Latest Build Download Link: https://github.com/Bram1903/AntiHealthIndicator/actions/runs/9413213246/artifacts/1578157884

I am going to release this patch in around an hour.

Kind regards,
Bram

**Comment by jd07159** [comment]
It doesn't work.

**Comment by Bram1903** [comment]
Huh? Are you sure you installed the latest build, and your config is up to date?

![2024-06-07_09 31 58](https://github.com/Bram1903/AntiHealthIndicator/assets/70259613/bb872478-f109-4ee4-8b8e-0ea3fe0766d4)

**Comment by jd07159** [comment]
Um sorry it works fine. I was watching myself on freecam.
Anyway, problem solved. thank you

**Comment by Bram1903** [comment]
I just released a new version that fixes the players-only setting issue (you already have that build). I am still looking into the Geyser problem.

**Comment by Bram1903** [comment]
The entity null bug is currently being worked on but requires some major changes to be applied. We will include it in the next patch!

**Comment by jd07159** [comment]
I just applied that plugin to proxy mode. There is no problem so far

**Comment by Bram1903** [comment]
> I just applied that plugin to proxy mode. There is no problem so far

Glad to hear that! Just so you know, PacketEvents currently has a few issues on 1.20.6 and 1.21 with the new wolf types, etc, but that will be fixed somewhere in the near future, and won't require a new release on my side. Just simply updating PacketEvents.
