### ISSUE TITLE
Network protocol error kick

### ISSUE THREAD

**Issue by Dawlnken** [Bram1903/AntiHealthIndicator#12]
My server is running 1.20.4 and when I join with 1.21 (viaversion installed on the server), i get a client disconnect. 

There is no errors in the console.

The error from my game log:

```
[12:20:35] [Render thread/ERROR]: Failed to handle packet aez[id=58999, packedItems=[c[id=9, serializer=ajx$$Lambda/0x00000133816cf678@4fa7df5c, value=0.5]]]
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 8
	at aka.a(SourceFile:116) ~[minecraft-1.21-client.jar:?]
	at fzg.a(SourceFile:553) ~[minecraft-1.21-client.jar:?]
	at aez.a(SourceFile:54) ~[minecraft-1.21-client.jar:?]
	at aez.a(SourceFile:12) ~[minecraft-1.21-client.jar:?]
	at zj.a(SourceFile:27) ~[minecraft-1.21-client.jar:?]
	at bph.d(SourceFile:162) [minecraft-1.21-client.jar:?]
	at bpl.d(SourceFile:23) [minecraft-1.21-client.jar:?]
	at bph.B(SourceFile:136) [minecraft-1.21-client.jar:?]
	at bph.bB(SourceFile:121) [minecraft-1.21-client.jar:?]
	at fgo.c(SourceFile:1240) [minecraft-1.21-client.jar:?]
	at fgo.f(SourceFile:882) [minecraft-1.21-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:256) [minecraft-1.21-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[12:20:35] [Render thread/WARN]: Client disconnected with reason: Network Protocol Error
```

Additional information: I was only disconnected when teleporting to a room with several entities (wolves, frames, paintings).

I don't have any mods installed.

**Comment by Bram1903** [comment]
@Dawlnken, could you give my latest release a go? It probably is not yet fixed, as I am awaiting a fix to be merged into PacketEvents, but perhaps it is now fixed by something I changed for Bungeecord that perhaps also fixed your issue. If not it will be fixed by PacketEvents soon.

**Comment by Bram1903** [comment]
This issue should be solved, and since no further comments have been placed, I will close it.
