### ISSUE TITLE
[Compatibility Issue] Custom mobs from MythicMobs and ModelEngine

### ISSUE THREAD

**Issue by TheFaik** [Bram1903/AntiHealthIndicator#14]
This happens when PacketEvents and AntiHealthIndicator are set. The player simply gets into the boat and gets kicked, and I also noticed that the player gets kicked because of mobs from MythicMobs and ModelEngine.
At the same time, there are no errors in the server logs, but there are errors on the client side. Here:
`---- Minecraft Network Protocol Error Report ----
// Are you sure you are not moving wrongly?

Time: 2024-07-13 00:20:31
Description: Packet handling error

java.lang.IllegalStateException: Invalid entity data item type for field 9 on entity class_1690['Дубовая лодка'/206, l='ClientLevel', x=-99.76, y=73.00, z=-2.49]: old=1(class java.lang.Integer), new=0.5(class java.lang.Float)
	at net.minecraft.class_2945.method_12785(class_2945.java:126)
	at net.minecraft.class_2945.method_12779(class_2945.java:117)
	at net.minecraft.class_634.method_11093(class_634.java:553)
	at net.minecraft.class_2739.method_11808(class_2739.java:54)
	at net.minecraft.class_2739.method_11054(class_2739.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2945.method_12785(class_2945.java:126)
	at net.minecraft.class_2945.method_12779(class_2945.java:117)
Mixins in Stacktrace: None found

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:set_entity_data
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

**Comment by TheFaik** [comment]
Server version: Leaf 1.21
Picture from the client's side:
![изображение](https://github.com/user-attachments/assets/1226796a-da38-4fb1-8df1-3304042125ba)

**Comment by Bram1903** [comment]
Hey there,

Thanks for your bug report. I will look into this over the weekend!

Kind regards,
Bram

**Comment by Bram1903** [comment]
Hey @TheFaik,

This has been fixed in the latest release: https://github.com/Bram1903/AntiHealthIndicator/releases/tag/v2.2.4

PS. I am not sure how to add compatibility with MythicMobs and ModelEngine, but I will look into that later, however, I am currently flooded with work and will go on vacation for 3 weeks in a few days.

Kind regards,
Bram

**Comment by TheFaik** [comment]
> Привет @TheFaik,
> 
> Это исправлено в последней версии: [ https://github.com/Bram1903/AntiHealthIndicator/releases/tag/v2.2.4. ](https://github.com/Bram1903/AntiHealthIndicator/releases/tag/v2.2.4)
> 
> ПС. Я не уверен, как добавить совместимость с MythicMobs и ModelEngine, но я рассмотрю это позже, однако в настоящее время я завален работой и через несколько дней уйду в отпуск на 3 недели.
> 
> С уважением, Брэм

Thank you. I'll check a little later.
