### ISSUE TITLE
NullPointerException on writePacket

### ISSUE THREAD

**Issue by HydrolienF** [Bram1903/AntiHealthIndicator#5]
I had a NullPointerException on writePacket.
I don't know what cause that exactly, last log on server was a player leaving.
```java
[20:56:51 ERROR]: Could not pass event VehicleExitEvent to AntiHealthIndicator v1.1.3
java.lang.NullPointerException: Cannot invoke "com.deathmotion.antihealthindicator.shaded.com.github.retrooper.packetevents.protocol.player.User.writePacket(com.deathmotion.antihealthindicator.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper)" because "user" is null
        at com.deathmotion.antihealthindicator.events.VehicleState.handleVehicleEvent(VehicleState.java:87) ~[AntiHealthIndicator-1.1.3.jar:?]
        at com.deathmotion.antihealthindicator.events.VehicleState.onExitRide(VehicleState.java:66) ~[AntiHealthIndicator-1.1.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor485.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"93b1a44"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"93b1a44"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"93b1a44"]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[?:git-UniverseSpigot-"93b1a44"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"93b1a44"]
```

**Comment by Bram1903** [comment]
Hello again,

I am not too sure how this can happen. It almost looks like the player left the moment PacketEvents sent the modified packet. At first, I perhaps thought it might be related to an entity other than a player leaving the horse, but I do check if the entity is of type player so that's not the case. I am at the moment rewriting this plugin as can be seen discussed in #4. I will close this for now as I hope this is a one-time occurrence besides the fact that the rewrite is almost finished.

Currently a bit busy because of university and other stuff, so I don't have as much time as I would like to work on projects like these. 

Kind regards,
Bram
